#!/usr/bin/env bash
# Launched by com.local.litellm.proxy — the always-on public gateway.
# Holds the stable aliases (main / coding / ocr) and routes them to the
# internal vllm-mlx backend and the on-demand GLM-OCR proxy. Apps talk only
# to this port (OpenAI /v1 + Anthropic /v1/messages); they never see the real
# model id, so an explicit model switch is invisible to them.
#
# The model_list is generated by setup.sh -> render_litellm_config() into
# /usr/local/etc/litellm.config.yaml whenever an alias assignment changes.
set -eu

CONF=/usr/local/etc/macstudio.conf
[ -r "$CONF" ] && . "$CONF"

VENV_DIR="${VENV_DIR:-/Users/mac/.macstudio-venvs}"
LITELLM_CONFIG=/usr/local/etc/litellm.config.yaml

export HOME="${TARGET_HOME:-/Users/mac}"
export USER="${TARGET_USER:-mac}"
export PATH="$VENV_DIR/litellm/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin"

exec "$VENV_DIR/litellm/bin/litellm" \
  --config "$LITELLM_CONFIG" \
  --host 0.0.0.0 \
  --port "${LITELLM_PORT:-11434}"
