#!/usr/bin/env bash
# Launched by com.local.litellm.proxy — the always-on public gateway.
# Holds the stable aliases (main / main-fast / embed / rerank, plus image/stt/tts
# when enabled) and routes them to the resident oMLX backend (and the on-demand
# image/voice backends). Apps talk only to this port (OpenAI /v1 + Anthropic
# /v1/messages); they never see the real model id, so a model switch is invisible.
#
# The model_list is generated by setup.sh -> render_litellm_config() into
# /usr/local/etc/litellm.config.yaml whenever an alias assignment changes.
set -eu

CONF=/usr/local/etc/macstudio.conf
[ -r "$CONF" ] && . "$CONF"

VENV_DIR="${VENV_DIR:-/Users/mac/.macstudio-venvs}"
LITELLM_CONFIG=/usr/local/etc/litellm.config.yaml

export HOME="${TARGET_HOME:-/Users/mac}"
export USER="${TARGET_USER:-mac}"
export PATH="$VENV_DIR/litellm/bin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin"

# Preconditions — fail with a clear pointer instead of a bare shell error.
if [ ! -x "$VENV_DIR/litellm/bin/litellm" ]; then
  echo "litellm venv missing ($VENV_DIR/litellm) — run: sudo bash setup.sh --apply" >&2
  exit 78
fi
if [ ! -r "$LITELLM_CONFIG" ]; then
  echo "litellm config missing ($LITELLM_CONFIG) — run: sudo bash setup.sh --apply" >&2
  exit 78
fi

exec "$VENV_DIR/litellm/bin/litellm" \
  --config "$LITELLM_CONFIG" \
  --host 0.0.0.0 \
  --port "${LITELLM_PORT:-11434}"
