#!/usr/bin/env python3
"""
Web dashboard for the MacStudio LLM Server — browser control of models,
services, settings, logs and telemetry. The SSH TUI (setup.sh) stays fully
authoritative; this daemon only shells out to setup.sh CLI verbs and to
whitelisted launchctl actions — it never reimplements bash logic.

Stdlib only (runs on /usr/bin/python3 as the launchd daemon
com.local.dashboard, as root — it reads `launchctl print system/*`, kickstarts
daemons and spawns setup.sh). ThreadingHTTPServer on 0.0.0.0:DASHBOARD_PORT.

Key design points (see CLAUDE.md):
  * Mutating jobs (--apply, --set-model, --download-model) run as DETACHED
    processes (start_new_session) with file-backed state under
    /var/log/macstudio/dashboard-jobs/ — a dashboard-triggered --apply
    restarts THIS daemon (service_py_label hot-restart / plist reload), so the
    job must not be our child-with-pipes. The plist sets AbandonProcessGroup.
    Job completion is detected via a `__JOB_RC__=<rc>` sentinel the /bin/sh
    wrapper appends to the job log. One mutating job at a time (409 else).
  * No SSE — cursor polling. /api/logs/<name>?offset=N and
    /api/jobs/<id>?offset=N return incremental bytes; the UI polls. Survives
    the self-restart above, no thread-lifecycle issues.
  * Auth: DASHBOARD_TOKEN from macstudio.conf (auto-generated by --apply).
    Login sets a stateless HMAC cookie derived from the token, so rotating
    the token invalidates every browser without a daemon restart. All /api/*
    (except /api/login) need the cookie or `Authorization: Bearer <token>`.
  * Telemetry: scrapes the silicon exporter (:9101) when INSTALL_EXPORTERS=1,
    and always samples the cheap basics itself (vm_stat/sysctl/ioreg). Ring
    buffer of ~1 h so charts fill instantly on page load.

Config via env (wrappers/start-dashboard.sh) + live re-reads of macstudio.conf:
  DASHBOARD_PORT   (the token is deliberately NOT passed via env — it is
                    re-read from the conf per request so rotation is instant)
"""
from __future__ import annotations

import hmac
import hashlib
import json
import os
import re
import shlex
import signal
import socket
import subprocess
import threading
import time
from collections import deque
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from urllib.parse import urlparse, parse_qs

# --- Fixed on-Mac paths (mirror setup.sh) ----------------------------------
CONF_FILE = "/usr/local/etc/macstudio.conf"
REPO_POINTER_FILE = "/usr/local/etc/macstudio.repo"
CATALOG_FILE = "/usr/local/etc/macstudio-models/catalog.tsv"
LOG_DIR = "/var/log/macstudio"
JOBS_DIR = os.path.join(LOG_DIR, "dashboard-jobs")
UI_FILE = "/usr/local/libexec/dashboard-ui.html"
APPLY_PENDING_MARKER = os.path.join(JOBS_DIR, "apply-pending")
DEFAULT_HF = "/Users/mac/.cache/huggingface"

LAUNCHCTL = "/bin/launchctl"
SYSCTL = "/usr/sbin/sysctl"
VM_STAT = "/usr/bin/vm_stat"
IOREG = "/usr/sbin/ioreg"
HOSTNAME_BIN = "/bin/hostname"

COOKIE_NAME = "macstudio_session"
SESSION_SALT = b"macstudio-dashboard-session-v1"
COOKIE_MAX_AGE = 30 * 24 * 3600

SAMPLE_INTERVAL = 10          # telemetry cadence (s)
HISTORY_SAMPLES = 360         # ~1 h at 10 s
SCHEMA_CACHE_SEC = 30
JOB_KEEP = 20                 # prune to the newest N jobs
LOG_CHUNK = 64 * 1024         # max bytes per incremental log read
TCP_PROBE_TIMEOUT = 0.3
LAUNCHCTL_TIMEOUT = 2.0

MEM_PRESSURE_LABEL = {1: "Normal", 2: "Warn", 4: "Critical"}
# Mirror set_model_alias's BROKEN refusal (bare BROKEN blocks everywhere;
# BROKEN[<engine>] only for that engine).
BARE_BROKEN_RE = re.compile(r"BROKEN([^[]|$)", re.IGNORECASE)
SAFE_LOG_RE = re.compile(r"^[A-Za-z0-9._-]+\.log$")
JOB_RC_RE = re.compile(r"^__JOB_RC__=(\d+)\s*$", re.MULTILINE)

# Service registry: label -> (German display name, kind). `kind` drives the UI
# actions (always-on -> restart/stop; on-demand -> wake/stop; scheduled -> none).
SERVICES = [
    ("com.local.mlxvlm.main",       "Text-Engine (mlx-vlm)",       "always"),
    ("com.local.litellm.proxy",     "LiteLLM-Gateway",             "always"),
    ("com.local.infinity.proxy",    "Embed/Rerank Proxy",          "always"),
    ("com.local.infinity.serve",    "Embed/Rerank Backend",        "ondemand"),
    ("com.local.immich.proxy",      "immich-ml Proxy",             "always"),
    ("com.local.immich.ml",         "immich-ml Backend",           "ondemand"),
    ("com.local.docling.proxy",     "docling Proxy",               "always"),
    ("com.local.docling.serve",     "docling Backend",             "ondemand"),
    ("com.local.node.exporter",     "Node-Exporter",               "always"),
    ("com.local.silicon.exporter",  "Silicon-Exporter",            "always"),
    ("com.local.ondemand.exporter", "On-Demand-Exporter",          "always"),
    ("com.local.llm.watchdog",      "Speicher-Watchdog",           "always"),
    ("com.local.preventsleep",      "Schlaf-Verhinderung",         "always"),
    ("com.local.iogpu.wiredlimit",  "GPU-Wired-Limit",             "scheduled"),
    ("com.local.weekly.autoupdate", "Wöchentliches Update",        "scheduled"),
    ("com.local.mqtt.bridge",       "MQTT-Bridge",                 "always"),
    ("com.local.dashboard",         "Web-Dashboard",               "always"),
    ("com.local.vncfilter",         "Remote Desktop (VNC-Filter)", "always"),
    ("com.local.novnc",             "Remote Desktop (noVNC)",      "always"),
    ("com.local.paperless.ocr",     "Paperless Apple-OCR",         "always"),
]
ALL_LABELS = {lbl for lbl, _n, _k in SERVICES}

# Services with a persistent power off/on control (frees memory for good vs.
# a transient stop that KeepAlive respawns instantly). Mirrors setup.sh's
# POWER_LABELS whitelist for --set-service-power.
POWER_LABELS = {"com.local.mlxvlm.main", "com.local.infinity.proxy"}

# label -> log file (mirror setup.sh label_log()).
LABEL_LOG = {
    "com.local.mlxvlm.main": "mlxvlm-main.log",
    "com.local.litellm.proxy": "litellm.log",
    "com.local.infinity.proxy": "infinity-proxy.log",
    "com.local.infinity.serve": "infinity-serve.log",
    "com.local.immich.proxy": "immich-proxy.log",
    "com.local.immich.ml": "immich-ml.log",
    "com.local.docling.proxy": "docling-proxy.log",
    "com.local.docling.serve": "docling-serve.log",
    "com.local.node.exporter": "node-exporter.log",
    "com.local.silicon.exporter": "silicon-exporter.log",
    "com.local.ondemand.exporter": "ondemand-exporter.log",
    "com.local.llm.watchdog": "watchdog.log",
    "com.local.preventsleep": "preventsleep.log",
    "com.local.iogpu.wiredlimit": "iogpu-wired-limit.log",
    "com.local.weekly.autoupdate": "autoupdate.log",
    "com.local.mqtt.bridge": "mqtt-bridge.log",
    "com.local.dashboard": "dashboard.log",
    "com.local.vncfilter": "vncfilter.log",
    "com.local.novnc": "novnc.log",
    "com.local.paperless.ocr": "paperless-ocr.log",
}


def log(msg):
    print(f"[{time.strftime('%F %T')}][dashboard] {msg}", flush=True)


def run_out(cmd, timeout=15):
    try:
        p = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)
    except Exception:
        return None
    if p.returncode != 0:
        return None
    return p.stdout.strip()


# ===========================================================================
# Config (mtime-cached live re-read — token rotation needs no restart)
# ===========================================================================
_conf_cache = {"mtime": 0.0, "data": {}}
_conf_lock = threading.Lock()


def conf():
    with _conf_lock:
        try:
            mt = os.stat(CONF_FILE).st_mtime
        except OSError:
            return dict(_conf_cache["data"])
        if mt != _conf_cache["mtime"]:
            data = {}
            try:
                with open(CONF_FILE) as f:
                    for line in f:
                        line = line.strip()
                        if not line or line.startswith("#") or "=" not in line:
                            continue
                        k, _, v = line.partition("=")
                        k, v = k.strip(), v.strip()
                        if len(v) >= 2 and v[0] == v[-1] and v[0] in ("'", '"'):
                            v = v[1:-1]
                        data[k] = v
            except OSError:
                data = dict(_conf_cache["data"])
            _conf_cache["mtime"] = mt
            _conf_cache["data"] = data
        return dict(_conf_cache["data"])


def conf_get(key, default=""):
    return conf().get(key, default) or default


def conf_flag(key, default="1"):
    return conf_get(key, default) == "1"


def active_labels():
    """Mirror load_config()'s ACTIVE_LABELS gates."""
    c = conf()
    mlx = c.get("INSTALL_MLX", "1") == "1"
    out = []
    for lbl, _name, _kind in SERVICES:
        if lbl == "com.local.mlxvlm.main":
            keep = mlx
        elif lbl.startswith("com.local.litellm."):
            keep = mlx
        elif lbl.startswith("com.local.infinity."):
            keep = c.get("INSTALL_EMBED", "1") == "1"
        elif lbl.startswith("com.local.immich."):
            keep = c.get("INSTALL_IMMICH", "1") == "1"
        elif lbl.startswith("com.local.docling."):
            keep = c.get("INSTALL_DOCLING", "1") == "1"
        elif lbl in ("com.local.node.exporter", "com.local.silicon.exporter",
                     "com.local.ondemand.exporter"):
            keep = c.get("INSTALL_EXPORTERS", "1") == "1"
        elif lbl == "com.local.llm.watchdog":
            keep = c.get("INSTALL_WATCHDOG", "1") == "1"
        elif lbl == "com.local.mqtt.bridge":
            keep = c.get("INSTALL_MQTT", "0") == "1"
        elif lbl == "com.local.dashboard":
            keep = c.get("INSTALL_DASHBOARD", "1") == "1"
        elif lbl == "com.local.vncfilter":
            keep = c.get("INSTALL_REMOTE", "1") == "1"
        elif lbl == "com.local.novnc":
            keep = c.get("INSTALL_NOVNC", "1") == "1" and c.get("INSTALL_REMOTE", "1") == "1"
        elif lbl == "com.local.paperless.ocr":
            keep = c.get("INSTALL_PAPERLESS_OCR", "0") == "1"
        else:
            keep = True
        if keep:
            out.append(lbl)
    return out


def find_setup_sh():
    try:
        with open(REPO_POINTER_FILE) as f:
            for line in f:
                if line.startswith("SETUP_SH="):
                    return line.split("=", 1)[1].strip()
    except OSError:
        pass
    return None


# ===========================================================================
# Collectors (adapted from mqtt-bridge.py)
# ===========================================================================
def launchctl_state(label):
    out = run_out([LAUNCHCTL, "print", f"system/{label}"], timeout=LAUNCHCTL_TIMEOUT)
    if out is None:
        return None, 0     # not loaded
    pid = 0
    for line in out.splitlines():
        m = re.match(r"\s*pid\s*=\s*(\d+)", line)
        if m:
            pid = int(m.group(1))
            break
    return (pid > 0), pid  # loaded: running / sleeping


# launchctl print-disabled prints `"<label>" => disabled` / `=> enabled`
# (NOT a `true`/`false` boolean — verified on-device).
_DISABLED_RE = re.compile(r'"([^"]+)"\s*=>\s*disabled')


def disabled_labels():
    """Labels with a persistent `launchctl disable` override (survives reboot
    and --apply). Only POWER_LABELS ever carry this override in practice."""
    out = run_out([LAUNCHCTL, "print-disabled", "system"], timeout=LAUNCHCTL_TIMEOUT)
    if out is None:
        return set()
    return set(_DISABLED_RE.findall(out))


def tcp_listening(port, host="127.0.0.1"):
    try:
        with socket.create_connection((host, int(port)), TCP_PROBE_TIMEOUT):
            return True
    except (OSError, ValueError):
        return False


def scrape_silicon(port):
    try:
        import urllib.request
        with urllib.request.urlopen(f"http://127.0.0.1:{port}/metrics", timeout=2) as r:
            body = r.read().decode("utf-8", "replace")
    except Exception:
        return None
    out = {}
    for line in body.splitlines():
        if line.startswith("#") or " " not in line:
            continue
        name, _, val = line.partition(" ")
        if "{" in name:
            continue
        out[name] = val
    return out


def _fv(d, key):
    if not d:
        return None
    try:
        return float(d[key])
    except (KeyError, ValueError):
        return None


def ram_free_mb():
    try:
        ps = int(run_out([SYSCTL, "-n", "hw.pagesize"]) or "0")
        out = run_out([VM_STAT]) or ""
        m = re.search(r"Pages free:\s+(\d+)", out)
        if ps and m:
            return (int(m.group(1)) * ps) // 1024 // 1024
    except Exception:
        pass
    return None


def total_ram_gb():
    try:
        b = int(run_out([SYSCTL, "-n", "hw.memsize"]) or "0")
        return round(b / 1024 / 1024 / 1024)
    except (TypeError, ValueError):
        return None


def wired_limit_mb():
    try:
        return int(run_out([SYSCTL, "-n", "iogpu.wired_limit_mb"]) or "")
    except (TypeError, ValueError):
        return None


def swap_used_mb():
    out = run_out([SYSCTL, "-n", "vm.swapusage"])
    if not out:
        return None
    m = re.search(r"used\s*=\s*([0-9.]+)([KMGT]?)", out)
    if not m:
        return None
    mult = {"K": 1 / 1024, "M": 1.0, "G": 1024.0, "T": 1024.0 * 1024}[m.group(2) or "M"]
    return round(float(m.group(1)) * mult, 1)


def gpu_mem_used_mb():
    out = run_out([IOREG, "-r", "-d", "1", "-c", "IOAccelerator"])
    if not out:
        return None
    m = re.search(r'"Alloc system memory"\s*=\s*(\d+)', out)
    if not m:
        return None
    return int(m.group(1)) // (1024 * 1024)


def mem_pressure_label():
    try:
        lvl = int(run_out([SYSCTL, "-n", "kern.memorystatus_vm_pressure_level"]) or "")
        return MEM_PRESSURE_LABEL.get(lvl, str(lvl))
    except (TypeError, ValueError):
        return None


def disk_free_gb(path):
    try:
        if not os.path.exists(path):
            path = "/"
        s = os.statvfs(path)
        return round(s.f_bavail * s.f_frsize / 1e9, 1)
    except OSError:
        return None


def boot_time_epoch():
    out = run_out([SYSCTL, "-n", "kern.boottime"])
    if not out:
        return None
    m = re.search(r"sec\s*=\s*(\d+)", out)
    return int(m.group(1)) if m else None


def host_name():
    return run_out([HOSTNAME_BIN]) or "localhost"


def is_broken_for(notes, engine):
    if BARE_BROKEN_RE.search(notes):
        return True
    return f"broken[{engine}]" in notes.lower()


def model_local_dir(repo, hf_cache):
    return os.path.join(hf_cache, "hub", "models--" + repo.replace("/", "--"))


def model_status(repo, hf_cache):
    d = model_local_dir(repo, hf_cache)
    snaps = os.path.join(d, "snapshots")
    has_st = False
    if os.path.isdir(snaps):
        for _root, _dirs, files in os.walk(snaps):
            if any(fn.endswith(".safetensors") for fn in files):
                has_st = True
                break
    if has_st:
        blobs = os.path.join(d, "blobs")
        if os.path.isdir(blobs):
            for _root, _dirs, files in os.walk(blobs):
                if any(fn.endswith(".incomplete") for fn in files):
                    return "partial"
        return "ok"
    return "partial" if os.path.isdir(d) else "none"


def model_downloaded_bytes(repo, hf_cache):
    """Bytes on disk under the repo's blobs dir (incl. .incomplete) — the
    live download-progress source while a --download-model job runs."""
    blobs = os.path.join(model_local_dir(repo, hf_cache), "blobs")
    total = 0
    try:
        for root, _dirs, files in os.walk(blobs):
            for fn in files:
                try:
                    total += os.path.getsize(os.path.join(root, fn))
                except OSError:
                    pass
    except OSError:
        pass
    return total


def read_catalog():
    rows = []
    try:
        with open(CATALOG_FILE) as f:
            for line in f:
                if line.startswith("#") or not line.strip():
                    continue
                cols = line.rstrip("\n").split("|")
                if len(cols) < 13:
                    continue
                cols += [""] * (17 - len(cols))
                rows.append({
                    "id": cols[0], "repo": cols[1], "role": cols[2],
                    "engine": cols[3], "quant": cols[4], "gb": cols[5],
                    "gated": cols[6], "reasoning_parser": cols[7],
                    "tool_parser": cols[8], "max_kv_size": cols[9],
                    "max_num_seqs": cols[10], "rating": cols[11],
                    "notes": cols[12], "temperature": cols[13],
                    "top_p": cols[14], "frequency_penalty": cols[15],
                    "presence_penalty": cols[16],
                })
    except OSError:
        pass
    return rows


# ===========================================================================
# Telemetry sampler (ring buffer)
# ===========================================================================
HISTORY = deque(maxlen=HISTORY_SAMPLES)
_history_lock = threading.Lock()


def take_sample():
    c = conf()
    sil = None
    if c.get("INSTALL_EXPORTERS", "1") == "1":
        sil = scrape_silicon(c.get("SILICON_EXPORTER_PORT", "9101") or "9101")
    sample = {
        "ts": int(time.time()),
        "exporter_up": sil is not None,
        "power_w": _fv(sil, "apple_silicon_sys_power_watts"),
        "cpu_temp_c": _fv(sil, "apple_silicon_cpu_temp_celsius"),
        "gpu_temp_c": _fv(sil, "apple_silicon_gpu_temp_celsius"),
        "gpu_active": _fv(sil, "apple_silicon_gpu_active_ratio"),
        "ram_free_mb": ram_free_mb(),
        "swap_used_mb": swap_used_mb(),
        "gpu_mem_mb": gpu_mem_used_mb(),
        "pressure": mem_pressure_label(),
    }
    return sample


def sampler_loop():
    while True:
        try:
            s = take_sample()
            with _history_lock:
                HISTORY.append(s)
        except Exception as exc:
            log(f"sampler error: {exc}")
        time.sleep(SAMPLE_INTERVAL)


# ===========================================================================
# Job manager (detached, disk-backed — survives our own restart)
# ===========================================================================
_jobs_lock = threading.Lock()
_job_counter = 0


def job_paths(job_id):
    return (os.path.join(JOBS_DIR, job_id + ".json"),
            os.path.join(JOBS_DIR, job_id + ".log"))


def read_job(job_id):
    jpath, lpath = job_paths(job_id)
    try:
        with open(jpath) as f:
            job = json.load(f)
    except (OSError, ValueError):
        return None
    if job.get("state") == "running":
        job = _refresh_job_state(job, lpath, jpath)
    return job


def _refresh_job_state(job, lpath, jpath):
    """Derive the live state: sentinel line in the log wins; else pid liveness."""
    rc = None
    try:
        with open(lpath, "rb") as f:
            f.seek(max(0, os.path.getsize(lpath) - 4096))
            tail = f.read().decode("utf-8", "replace")
        m = None
        for m in JOB_RC_RE.finditer(tail):
            pass
        if m:
            rc = int(m.group(1))
    except OSError:
        pass
    if rc is None:
        try:
            os.kill(job["pid"], 0)
            return job  # still running
        except (OSError, KeyError):
            rc = -1     # died without sentinel (killed / crashed)
    job["state"] = "done" if rc == 0 else "failed"
    job["rc"] = rc
    job["ended"] = int(time.time())
    try:
        with open(jpath, "w") as f:
            json.dump(job, f)
    except OSError:
        pass
    return job


def list_jobs():
    try:
        names = [n[:-5] for n in os.listdir(JOBS_DIR) if n.endswith(".json")]
    except OSError:
        return []
    jobs = [j for j in (read_job(n) for n in sorted(names, reverse=True)) if j]
    jobs.sort(key=lambda j: j.get("started", 0), reverse=True)
    return jobs


def active_job():
    for j in list_jobs():
        if j.get("state") == "running":
            return j
    return None


def prune_jobs():
    jobs = list_jobs()
    for j in jobs[JOB_KEEP:]:
        if j.get("state") == "running":
            continue
        jpath, lpath = job_paths(j["id"])
        for p in (jpath, lpath):
            try:
                os.remove(p)
            except OSError:
                pass


def start_job(kind, title, argv, meta=None):
    """Spawn `argv` fully detached; returns (job, None) or (None, error)."""
    global _job_counter
    with _jobs_lock:
        running = active_job()
        if running:
            return None, running
        _job_counter += 1
        job_id = time.strftime("%Y%m%d-%H%M%S") + f"-{_job_counter:02d}-{kind}"
        jpath, lpath = job_paths(job_id)
        cmd = " ".join(shlex.quote(a) for a in argv)
        # The /bin/sh wrapper appends the rc sentinel to the SAME log so a
        # dashboard restart mid-job can still tell how it ended.
        sh = f'{cmd}; echo "__JOB_RC__=$?"'
        env = {
            "PATH": "/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/bin:/usr/local/bin",
            "HOME": "/var/root",
        }
        try:
            logf = open(lpath, "ab")
        except OSError as exc:
            return None, {"error": f"job log unwritable: {exc}"}
        try:
            p = subprocess.Popen(
                ["/bin/sh", "-c", sh],
                stdout=logf, stderr=subprocess.STDOUT,
                stdin=subprocess.DEVNULL,
                start_new_session=True,   # detach: survives our kickstart
                env=env, cwd="/",
            )
        except OSError as exc:
            logf.close()
            return None, {"error": f"spawn failed: {exc}"}
        finally:
            try:
                logf.close()
            except OSError:
                pass
        job = {
            "id": job_id, "kind": kind, "title": title, "argv": argv,
            "pid": p.pid, "pgid": p.pid, "started": int(time.time()),
            "state": "running", "meta": meta or {},
        }
        try:
            with open(jpath, "w") as f:
                json.dump(job, f)
        except OSError as exc:
            return None, {"error": f"job state unwritable: {exc}"}
        prune_jobs()
        log(f"job started: {job_id} pid={p.pid} :: {cmd}")
        return job, None


def cancel_job(job_id):
    job = read_job(job_id)
    if not job:
        return False, "unbekannter Job"
    if job.get("state") != "running":
        return False, "Job läuft nicht mehr"
    try:
        os.killpg(job["pgid"], signal.SIGTERM)
    except OSError as exc:
        return False, f"killpg fehlgeschlagen: {exc}"
    log(f"job cancelled: {job_id}")
    return True, None


def read_tail_lines(path, lines, max_bytes=2 * 1024 * 1024):
    """Last N lines of a file in ONE read (initial log view). Returns the
    same shape as read_incremental with next_offset = size, so the UI can
    continue polling incrementally from the end."""
    try:
        size = os.path.getsize(path)
    except OSError:
        return {"data": "", "next_offset": 0, "size": 0, "missing": True}
    want = min(size, max(LOG_CHUNK, lines * 300), max_bytes)
    try:
        with open(path, "rb") as f:
            f.seek(size - want)
            raw = f.read(want)
    except OSError:
        return {"data": "", "next_offset": size, "size": size}
    text = raw.decode("utf-8", "replace")
    all_lines = text.splitlines(True)
    if size > want and all_lines:
        all_lines = all_lines[1:]      # drop the likely-partial first line
    return {"data": "".join(all_lines[-lines:]), "next_offset": size, "size": size}


def read_incremental(path, offset, limit=LOG_CHUNK):
    """Rotation-aware cursor read: size < offset -> reset to 0."""
    try:
        size = os.path.getsize(path)
    except OSError:
        return {"data": "", "next_offset": 0, "size": 0, "missing": True}
    if offset > size:
        offset = 0
    try:
        with open(path, "rb") as f:
            f.seek(offset)
            raw = f.read(limit)
    except OSError:
        return {"data": "", "next_offset": offset, "size": size}
    return {
        "data": raw.decode("utf-8", "replace"),
        "next_offset": offset + len(raw),
        "size": size,
    }


# ===========================================================================
# setup.sh invocations (sync — quick verbs only; slow ones go through jobs)
# ===========================================================================
def setup_sync(args, timeout=60, stdin_text=None):
    setup = find_setup_sh()
    if not setup:
        return 1, "setup.sh nicht gefunden (macstudio.repo fehlt)"
    env = {
        "PATH": "/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/bin:/usr/local/bin",
        "HOME": "/var/root",
    }
    try:
        p = subprocess.run(
            ["/bin/bash", setup] + args,
            capture_output=True, text=True, timeout=timeout,
            input=stdin_text, env=env, cwd="/",
        )
    except subprocess.TimeoutExpired:
        return 1, f"Timeout nach {timeout} s"
    except OSError as exc:
        return 1, str(exc)
    out = (p.stdout or "") + (p.stderr or "")
    return p.returncode, out.strip()


_schema_cache = {"ts": 0.0, "data": None}


def config_schema():
    now = time.time()
    if _schema_cache["data"] is not None and now - _schema_cache["ts"] < SCHEMA_CACHE_SEC:
        return _schema_cache["data"]
    rc, out = setup_sync(["--config-schema"], timeout=30)
    if rc != 0:
        return _schema_cache["data"] or []
    rows = []
    for line in out.splitlines():
        parts = line.split("\t")
        if len(parts) < 2 or not parts[0]:
            continue
        parts += [""] * (4 - len(parts))
        rows.append({"key": parts[0], "value": parts[1],
                     "default": parts[2], "hint": parts[3]})
    _schema_cache["ts"] = now
    _schema_cache["data"] = rows
    return rows


def invalidate_schema_cache():
    _schema_cache["ts"] = 0.0
    _schema_cache["data"] = None


def apply_pending():
    return os.path.isfile(APPLY_PENDING_MARKER)


def set_apply_pending(flag):
    try:
        if flag:
            with open(APPLY_PENDING_MARKER, "w") as f:
                f.write(str(int(time.time())))
        else:
            if os.path.isfile(APPLY_PENDING_MARKER):
                os.remove(APPLY_PENDING_MARKER)
    except OSError:
        pass


# ===========================================================================
# API payload builders
# ===========================================================================
def api_status():
    c = conf()
    labels = active_labels()
    disabled = disabled_labels()
    services = []
    for lbl, name, kind in SERVICES:
        if lbl not in labels:
            continue
        running, pid = launchctl_state(lbl)
        if running is None:
            state = "absent"
        elif running:
            state = "running"
        else:
            state = "sleeping"
        services.append({
            "label": lbl, "name": name, "kind": kind,
            "state": state, "pid": pid,
            "log": LABEL_LOG.get(lbl, lbl.replace("com.local.", "") + ".log"),
            "power": lbl in POWER_LABELS,
            "disabled": lbl in disabled,
        })
    job = active_job()
    return {
        "hostname": host_name(),
        "time": int(time.time()),
        "boot_epoch": boot_time_epoch(),
        "engine": c.get("TEXT_ENGINE", "mlx-vlm"),
        "aliases": {
            "main": c.get("ALIAS_MAIN", ""),
            "main_fast": c.get("PRESET_ALIASES", "1") == "1",
            "embed": c.get("ALIAS_EMBED", ""),
            "rerank": c.get("ALIAS_RERANK", ""),
        },
        "gateway_up": tcp_listening(c.get("LITELLM_PORT", "11434") or "11434"),
        "gateway_port": c.get("LITELLM_PORT", "11434"),
        "memory": {
            "ram_free_mb": ram_free_mb(),
            "total_ram_gb": total_ram_gb(),
            "wired_limit_mb": wired_limit_mb(),
            "swap_used_mb": swap_used_mb(),
            "gpu_mem_mb": gpu_mem_used_mb(),
            "pressure": mem_pressure_label(),
        },
        "disk_free_gb": disk_free_gb(c.get("HF_CACHE_DIR", DEFAULT_HF) or DEFAULT_HF),
        "exporters_on": c.get("INSTALL_EXPORTERS", "1") == "1",
        "apply_pending": apply_pending(),
        "active_job": job,
        "services": services,
    }


def api_models():
    c = conf()
    hf = c.get("HF_CACHE_DIR", DEFAULT_HF) or DEFAULT_HF
    engine = c.get("TEXT_ENGINE", "mlx-vlm") or "mlx-vlm"
    rows = []
    for r in read_catalog():
        st = model_status(r["repo"], hf)
        notes = r["notes"]
        row = dict(r)
        row["status"] = st
        # Real on-disk size (bytes) for downloaded models — the UI shows it when
        # the catalog's gb column is unknown ("?"). Display-only; the TUI-owned
        # catalog is never rewritten.
        row["disk_bytes"] = model_downloaded_bytes(r["repo"], hf) if st in ("ok", "partial") else 0
        row["broken_main"] = is_broken_for(notes, "mlx-vlm") if r["role"] == "text" else None
        if r["role"] in ("embed", "rerank"):
            row["broken"] = is_broken_for(notes, "infinity")
        else:
            row["broken"] = row["broken_main"]
        row["slots"] = [s for s, key in (
            ("main", "ALIAS_MAIN"),
            ("embed", "ALIAS_EMBED"), ("rerank", "ALIAS_RERANK"),
        ) if c.get(key, "") == r["id"]]
        rows.append(row)
    hf_token = os.path.isfile(os.path.join(hf, "token"))
    return {
        "engine": engine,
        "hf_token_set": hf_token, "models": rows,
    }


def api_telemetry():
    with _history_lock:
        hist = list(HISTORY)
    now = hist[-1] if hist else take_sample()
    out = {"now": now, "history": hist, "interval_sec": SAMPLE_INTERVAL}
    # Live download progress while a --download-model job runs.
    job = active_job()
    if job and job.get("kind") == "download":
        meta = job.get("meta") or {}
        repo = meta.get("repo")
        if repo:
            c = conf()
            hf = c.get("HF_CACHE_DIR", DEFAULT_HF) or DEFAULT_HF
            out["download"] = {
                "job_id": job["id"], "model_id": meta.get("id"),
                "bytes": model_downloaded_bytes(repo, hf),
                "approx_gb": meta.get("gb"),
            }
    return out


def api_job_detail(job_id, offset):
    job = read_job(job_id)
    if not job:
        return None
    _jp, lpath = job_paths(job_id)
    chunk = read_incremental(lpath, offset)
    out = {"job": job, "log": chunk}
    if job.get("kind") == "download":
        meta = job.get("meta") or {}
        repo = meta.get("repo")
        if repo:
            c = conf()
            hf = c.get("HF_CACHE_DIR", DEFAULT_HF) or DEFAULT_HF
            out["progress"] = {
                "bytes": model_downloaded_bytes(repo, hf),
                "approx_gb": meta.get("gb"),
            }
    # A finished apply clears the pending flag.
    if job.get("kind") == "apply" and job.get("state") == "done":
        set_apply_pending(False)
    return out


# ===========================================================================
# HTTP layer
# ===========================================================================
_ui_cache = {"mtime": 0.0, "body": b""}
_ui_lock = threading.Lock()


def api_links():
    """Useful endpoints/links, computed from the live config. The browser builds the
    hrefs from its own hostname so they point at the same Mac the dashboard is on."""
    c = conf()

    def port(k, d):
        try:
            return int(c.get(k, d))
        except ValueError:
            return int(d)

    return {
        "litellm_port": port("LITELLM_PORT", 11434),
        "docling_port": port("DOCLING_PUBLIC_PORT", 5001) if c.get("INSTALL_DOCLING", "1") == "1" else 0,
        "infinity_port": port("INFINITY_PUBLIC_PORT", 5004) if c.get("INSTALL_EMBED", "1") == "1" else 0,
        "vnc_enabled": c.get("INSTALL_REMOTE", "1") == "1",
        "vnc_filter_port": port("VNC_FILTER_PORT", 5901) if c.get("INSTALL_REMOTE", "1") == "1" else 0,
        "novnc_port": port("NOVNC_PORT", 6080) if (c.get("INSTALL_REMOTE", "1") == "1" and c.get("INSTALL_NOVNC", "1") == "1") else 0,
        "paperless_ocr": c.get("INSTALL_PAPERLESS_OCR", "0") == "1",
        "smb_shared": c.get("PAPERLESS_OCR_SMB_SHARE", "0") == "1",
        "smb_name": c.get("PAPERLESS_OCR_SMB_NAME", "inbox"),
        "duplex_sub": c.get("PAPERLESS_OCR_DUPLEX_SUBDIR", "duplex"),
        "paperless_url": c.get("PAPERLESS_OCR_URL", ""),
        "repo": "https://github.com/AHEMOH/macstudio-llm",
    }


def _po_dirs():
    c = conf()
    inbox = c.get("PAPERLESS_OCR_INBOX", "/Users/mac/paperless-ocr/inbox")
    parent = os.path.dirname(inbox)
    return {
        "inbox": inbox,
        "duplex": os.path.join(inbox, c.get("PAPERLESS_OCR_DUPLEX_SUBDIR", "duplex")),
        "originals": c.get("PAPERLESS_OCR_ARCHIVE", os.path.join(parent, "originals")),
        "errors": c.get("PAPERLESS_OCR_ERRORS", os.path.join(parent, "errors")),
    }


def _po_list(path, stable_sec, mark_pending):
    out = []
    try:
        names = sorted(os.listdir(path))
    except OSError:
        return out
    now = time.time()
    for n in names:
        if n.startswith("."):
            continue
        fp = os.path.join(path, n)
        if not os.path.isfile(fp):
            continue
        try:
            st = os.stat(fp)
        except OSError:
            continue
        item = {"name": n, "size": st.st_size, "age": int(now - st.st_mtime)}
        if mark_pending:
            item["status"] = "pending" if item["age"] < stable_sec else "ready"
        out.append(item)
    return out


def api_paperless_ocr():
    c = conf()
    try:
        stable = int(c.get("PAPERLESS_OCR_STABLE_SEC", "30"))
    except ValueError:
        stable = 30
    d = _po_dirs()
    return {
        "enabled": c.get("INSTALL_PAPERLESS_OCR", "0") == "1",
        "configured": bool(c.get("PAPERLESS_OCR_URL", "")) and bool(c.get("PAPERLESS_OCR_TOKEN", "")),
        "langs": c.get("PAPERLESS_OCR_LANGS", "").replace("\\", ""),
        "stable_sec": stable,
        "smb_shared": c.get("PAPERLESS_OCR_SMB_SHARE", "0") == "1",
        "smb_name": c.get("PAPERLESS_OCR_SMB_NAME", "inbox"),
        "duplex_sub": c.get("PAPERLESS_OCR_DUPLEX_SUBDIR", "duplex"),
        "folders": {
            "inbox": _po_list(d["inbox"], stable, True),
            "duplex": _po_list(d["duplex"], stable, True),
            "originals": _po_list(d["originals"], stable, False),
            "errors": _po_list(d["errors"], stable, False),
        },
    }


def po_action(folder, name, action):
    """Delete or re-queue a single paperless-ocr file. Path-traversal-safe: the target
    must be a regular file whose parent is exactly the configured folder."""
    dirs = _po_dirs()
    if folder not in dirs:
        return (False, "unbekannter Ordner")
    base = os.path.realpath(dirs[folder])
    target = os.path.realpath(os.path.join(base, os.path.basename(name or "")))
    if os.path.dirname(target) != base or not os.path.isfile(target):
        return (False, "ungültige Datei")
    try:
        if action == "delete":
            os.remove(target)
            return (True, "gelöscht")
        if action == "requeue":
            inbox = os.path.realpath(dirs["inbox"])
            os.rename(target, os.path.join(inbox, os.path.basename(name)))
            return (True, "in Inbox verschoben")
    except OSError as e:
        return (False, str(e))
    return (False, "unbekannte Aktion")


def ui_body():
    with _ui_lock:
        try:
            mt = os.stat(UI_FILE).st_mtime
        except OSError:
            return None
        if mt != _ui_cache["mtime"]:
            try:
                with open(UI_FILE, "rb") as f:
                    _ui_cache["body"] = f.read()
                _ui_cache["mtime"] = mt
            except OSError:
                return None
        return _ui_cache["body"]


def session_for(token):
    return hmac.new(token.encode("utf-8"), SESSION_SALT, hashlib.sha256).hexdigest()


class Handler(BaseHTTPRequestHandler):
    server_version = "macstudio-dashboard"
    protocol_version = "HTTP/1.1"

    def log_message(self, fmt, *args):
        pass

    # -- helpers -------------------------------------------------------------
    def send_json(self, obj, code=200, extra_headers=None):
        body = json.dumps(obj).encode("utf-8")
        self.send_response(code)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        for k, v in (extra_headers or {}).items():
            self.send_header(k, v)
        self.end_headers()
        try:
            self.wfile.write(body)
        except OSError:
            pass

    def read_body_json(self):
        try:
            n = int(self.headers.get("Content-Length", "0") or "0")
        except ValueError:
            n = 0
        if n <= 0 or n > 1024 * 1024:
            return {}
        try:
            return json.loads(self.rfile.read(n).decode("utf-8"))
        except (OSError, ValueError):
            return {}

    def cookie_value(self):
        raw = self.headers.get("Cookie", "") or ""
        for part in raw.split(";"):
            k, _, v = part.strip().partition("=")
            if k == COOKIE_NAME:
                return v
        return ""

    def authed(self):
        token = conf_get("DASHBOARD_TOKEN")
        if not token:
            return False
        auth = self.headers.get("Authorization", "") or ""
        if auth.startswith("Bearer "):
            if hmac.compare_digest(auth[7:].strip(), token):
                return True
        cookie = self.cookie_value()
        if cookie and hmac.compare_digest(cookie, session_for(token)):
            return True
        return False

    def deny(self):
        self.send_json({"error": "nicht angemeldet"}, code=401)

    def busy_409(self, job):
        self.send_json({"error": "Ein Vorgang läuft bereits", "active_job": job}, code=409)

    # -- GET -----------------------------------------------------------------
    def do_GET(self):
        parsed = urlparse(self.path)
        path = parsed.path
        qs = parse_qs(parsed.query)

        if path == "/" or path == "/index.html":
            body = ui_body()
            if body is None:
                body = ("<h1>Dashboard-UI fehlt</h1><p>dashboard-ui.html nicht gefunden — "
                        "<code>sudo bash setup.sh --apply</code> ausführen.</p>").encode("utf-8")
            self.send_response(200)
            self.send_header("Content-Type", "text/html; charset=utf-8")
            self.send_header("Content-Length", str(len(body)))
            self.send_header("Cache-Control", "no-cache")
            self.end_headers()
            try:
                self.wfile.write(body)
            except OSError:
                pass
            return

        if not path.startswith("/api/"):
            self.send_json({"error": "not found"}, code=404)
            return
        if not self.authed():
            self.deny()
            return

        try:
            offset = int(qs.get("offset", ["0"])[0])
        except ValueError:
            offset = 0

        if path == "/api/status":
            self.send_json(api_status())
        elif path == "/api/models":
            self.send_json(api_models())
        elif path == "/api/telemetry":
            self.send_json(api_telemetry())
        elif path == "/api/paperless-ocr":
            self.send_json(api_paperless_ocr())
        elif path == "/api/links":
            self.send_json(api_links())
        elif path == "/api/config":
            self.send_json({"schema": config_schema(), "apply_pending": apply_pending()})
        elif path == "/api/jobs":
            self.send_json({"jobs": list_jobs()})
        elif path.startswith("/api/jobs/"):
            job_id = os.path.basename(path[len("/api/jobs/"):])
            detail = api_job_detail(job_id, offset)
            if detail is None:
                self.send_json({"error": "unbekannter Job"}, code=404)
            else:
                self.send_json(detail)
        elif path == "/api/logs":
            files = []
            try:
                for fn in sorted(os.listdir(LOG_DIR)):
                    if not fn.endswith(".log"):
                        continue
                    p = os.path.join(LOG_DIR, fn)
                    try:
                        st = os.stat(p)
                        files.append({"name": fn, "size": st.st_size,
                                      "mtime": int(st.st_mtime)})
                    except OSError:
                        pass
            except OSError:
                pass
            self.send_json({"logs": files})
        elif path.startswith("/api/logs/"):
            name = path[len("/api/logs/"):]
            if not SAFE_LOG_RE.match(name):
                self.send_json({"error": "ungültiger Log-Name"}, code=400)
                return
            full = os.path.realpath(os.path.join(LOG_DIR, name))
            if not full.startswith(os.path.realpath(LOG_DIR) + os.sep):
                self.send_json({"error": "ungültiger Pfad"}, code=400)
                return
            # No offset -> initial view: last N lines in one shot (default
            # 1000). With offset -> incremental follow-up read.
            if "offset" not in qs:
                try:
                    lines = int(qs.get("lines", ["1000"])[0])
                except ValueError:
                    lines = 1000
                lines = max(10, min(lines, 20000))
                self.send_json(read_tail_lines(full, lines))
            else:
                self.send_json(read_incremental(full, offset))
        else:
            self.send_json({"error": "not found"}, code=404)

    # -- POST ----------------------------------------------------------------
    def do_POST(self):
        parsed = urlparse(self.path)
        path = parsed.path

        if path == "/api/login":
            self.handle_login()
            return
        if not self.authed():
            self.deny()
            return
        if path == "/api/logout":
            self.send_json({"ok": True}, extra_headers={
                "Set-Cookie": f"{COOKIE_NAME}=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0"})
            return

        body = self.read_body_json()

        if path == "/api/models/select":
            self.handle_model_select(body)
        elif path == "/api/models/add":
            self.handle_model_add(body)
        elif path == "/api/models/edit":
            self.handle_model_edit(body)
        elif path == "/api/models/download":
            self.handle_model_download(body)
        elif path == "/api/models/delete":
            self.handle_sync_guarded(
                lambda: setup_sync(["--delete-model", str(body.get("id", ""))], timeout=120))
        elif path == "/api/models/remove":
            self.handle_sync_guarded(
                lambda: setup_sync(["--remove-model", str(body.get("id", ""))], timeout=30))
        elif path == "/api/hf-token":
            self.handle_sync_guarded(
                lambda: setup_sync(["--set-hf-token"], timeout=60,
                                   stdin_text=str(body.get("token", "")) + "\n"))
        elif path == "/api/config":
            self.handle_config_save(body)
        elif path == "/api/apply":
            self.handle_apply()
        elif path.startswith("/api/jobs/") and path.endswith("/cancel"):
            job_id = os.path.basename(path[len("/api/jobs/"):-len("/cancel")].strip("/"))
            ok, err = cancel_job(job_id)
            if ok:
                self.send_json({"ok": True})
            else:
                self.send_json({"error": err}, code=400)
        elif path.startswith("/api/services/"):
            self.handle_service_action(path)
        elif path == "/api/paperless-ocr/action":
            ok, msg = po_action(body.get("folder"), body.get("name"), body.get("action"))
            self.send_json({"ok": ok, "msg": msg}, code=200 if ok else 400)
        else:
            self.send_json({"error": "not found"}, code=404)

    # -- POST handlers ---------------------------------------------------------
    def handle_login(self):
        body = self.read_body_json()
        token = conf_get("DASHBOARD_TOKEN")
        given = str(body.get("token", ""))
        if not token or not given or not hmac.compare_digest(given, token):
            time.sleep(1.0)  # brute-force friction
            self.send_json({"error": "falscher Token"}, code=401)
            return
        cookie = (f"{COOKIE_NAME}={session_for(token)}; HttpOnly; SameSite=Strict; "
                  f"Path=/; Max-Age={COOKIE_MAX_AGE}")
        self.send_json({"ok": True}, extra_headers={"Set-Cookie": cookie})

    def handle_sync_guarded(self, fn):
        """Run a quick sync setup.sh verb — refused while a job runs."""
        job = active_job()
        if job:
            self.busy_409(job)
            return
        rc, out = fn()
        if rc == 0:
            self.send_json({"ok": True, "output": out})
        else:
            self.send_json({"error": last_lines(out), "output": out}, code=400)

    def handle_model_select(self, body):
        slot = str(body.get("slot", ""))
        mid = str(body.get("id", ""))
        if slot not in ("main", "embed", "rerank"):
            self.send_json({"error": f"ungültiger Slot: {slot}"}, code=400)
            return
        setup = find_setup_sh()
        if not setup:
            self.send_json({"error": "setup.sh nicht gefunden"}, code=500)
            return
        job, busy = start_job(
            "set-model", f"Modell wechseln: {slot} → {mid}",
            ["/bin/bash", setup, "--set-model", slot, mid],
            meta={"slot": slot, "id": mid})
        if job is None:
            if busy and "error" in busy:
                self.send_json(busy, code=500)
            else:
                self.busy_409(busy)
            return
        self.send_json({"job_id": job["id"]})

    def handle_model_add(self, body):
        job = active_job()
        if job:
            self.busy_409(job)
            return
        mid = str(body.get("id", "")).strip()
        repo = str(body.get("repo", "")).strip()
        role = str(body.get("role", "text")).strip() or "text"
        engine = str(body.get("engine", "")).strip()
        gb = str(body.get("gb", "")).strip()
        gated = "yes" if body.get("gated") in (True, "yes", "1", 1) else "no"
        if not mid or not repo:
            self.send_json({"error": "ID und HF-Repo sind erforderlich"}, code=400)
            return
        args = ["--add-model", "id=" + mid, "repo=" + repo, "role=" + role, "gated=" + gated]
        if engine:
            args.append("engine=" + engine)
        if gb:
            args.append("gb=" + gb)
        rc, out = setup_sync(args, timeout=30)
        if rc == 0:
            self.send_json({"ok": True, "id": mid, "output": out})
        else:
            self.send_json({"error": last_lines(out), "output": out}, code=400)

    def handle_model_edit(self, body):
        job = active_job()
        if job:
            self.busy_409(job)
            return
        mid = str(body.get("id", "")).strip()
        if not mid:
            self.send_json({"error": "ID fehlt"}, code=400)
            return
        # Map JSON fields → --edit-model key=value args (only those present).
        field_map = [
            ("repo", "repo"), ("role", "role"), ("engine", "engine"),
            ("quant", "quant"), ("gb", "gb"), ("gated", "gated"),
            ("reasoning_parser", "reasoning"), ("tool_parser", "tool"),
            ("max_kv_size", "max_kv"), ("max_num_seqs", "max_seqs"),
            ("rating", "rating"), ("notes", "notes"), ("temperature", "temp"),
            ("top_p", "top_p"), ("frequency_penalty", "freq"),
            ("presence_penalty", "pres"),
        ]
        args = ["--edit-model", "id=" + mid]
        for json_key, cli_key in field_map:
            if json_key in body and body[json_key] is not None:
                val = str(body[json_key])
                if "|" in val:
                    self.send_json({"error": f"Feld '{json_key}' darf kein '|' enthalten"}, code=400)
                    return
                args.append(cli_key + "=" + val)
        rc, out = setup_sync(args, timeout=30)
        if rc == 0:
            self.send_json({"ok": True, "output": out})
        else:
            self.send_json({"error": last_lines(out), "output": out}, code=400)

    def handle_model_download(self, body):
        mid = str(body.get("id", ""))
        row = next((r for r in read_catalog() if r["id"] == mid), None)
        if row is None:
            self.send_json({"error": f"unbekannte Modell-ID: {mid}"}, code=400)
            return
        setup = find_setup_sh()
        if not setup:
            self.send_json({"error": "setup.sh nicht gefunden"}, code=500)
            return
        job, busy = start_job(
            "download", f"Modell herunterladen: {mid}",
            ["/bin/bash", setup, "--download-model", mid],
            meta={"id": mid, "repo": row["repo"], "gb": row["gb"]})
        if job is None:
            if busy and "error" in busy:
                self.send_json(busy, code=500)
            else:
                self.busy_409(busy)
            return
        self.send_json({"job_id": job["id"]})

    def handle_config_save(self, body):
        job = active_job()
        if job:
            self.busy_409(job)
            return
        changes = body.get("changes") or {}
        if not isinstance(changes, dict) or not changes:
            self.send_json({"error": "keine Änderungen übergeben"}, code=400)
            return
        saved, errors = [], []
        for key, value in changes.items():
            rc, out = setup_sync(["--set-config", str(key), str(value)], timeout=30)
            if rc == 0:
                saved.append(key)
            else:
                errors.append({"key": key, "error": last_lines(out)})
        invalidate_schema_cache()
        if saved:
            set_apply_pending(True)
        if errors:
            self.send_json({"saved": saved, "errors": errors}, code=400)
        else:
            self.send_json({"ok": True, "saved": saved, "apply_pending": True})

    def handle_apply(self):
        setup = find_setup_sh()
        if not setup:
            self.send_json({"error": "setup.sh nicht gefunden"}, code=500)
            return
        job, busy = start_job(
            "apply", "Konfiguration anwenden (setup.sh --apply)",
            ["/bin/bash", setup, "--apply"])
        if job is None:
            if busy and "error" in busy:
                self.send_json(busy, code=500)
            else:
                self.busy_409(busy)
            return
        self.send_json({"job_id": job["id"]})

    def handle_service_action(self, path):
        # /api/services/<label>/<action>
        rest = path[len("/api/services/"):]
        parts = [p for p in rest.split("/") if p]
        if len(parts) != 2:
            self.send_json({"error": "not found"}, code=404)
            return
        label, action = parts
        if label not in ALL_LABELS:
            self.send_json({"error": f"unbekanntes Label: {label}"}, code=400)
            return
        if action not in ("restart", "stop", "wake", "poweron", "poweroff"):
            self.send_json({"error": f"unbekannte Aktion: {action}"}, code=400)
            return
        if action in ("poweron", "poweroff") and label not in POWER_LABELS:
            self.send_json({"error": f"Power-Steuerung nicht verfügbar für: {label}"}, code=400)
            return
        job = active_job()
        if job:
            self.busy_409(job)
            return
        if action in ("poweron", "poweroff"):
            want = "on" if action == "poweron" else "off"
            rc, out = setup_sync(["--set-service-power", label, want], timeout=30)
            if rc == 0:
                log(f"service {action}: {label}")
                self.send_json({"ok": True})
            else:
                self.send_json({"error": out or f"setup.sh rc={rc}"}, code=500)
            return
        if action in ("restart", "wake"):
            cmd = [LAUNCHCTL, "kickstart", "-k", f"system/{label}"]
        else:
            cmd = [LAUNCHCTL, "stop", label]
        try:
            p = subprocess.run(cmd, capture_output=True, text=True, timeout=15)
        except Exception as exc:
            self.send_json({"error": str(exc)}, code=500)
            return
        if p.returncode == 0:
            log(f"service {action}: {label}")
            self.send_json({"ok": True})
        else:
            msg = (p.stderr or p.stdout or "").strip() or f"launchctl rc={p.returncode}"
            self.send_json({"error": msg}, code=500)


def last_lines(text, n=3):
    lines = [ln for ln in (text or "").splitlines() if ln.strip()]
    return " / ".join(lines[-n:]) if lines else "unbekannter Fehler"


# ===========================================================================
# Main
# ===========================================================================
def main():
    port = int(os.environ.get("DASHBOARD_PORT", "8090") or 8090)
    try:
        os.makedirs(JOBS_DIR, exist_ok=True)
    except OSError as exc:
        log(f"cannot create {JOBS_DIR}: {exc}")
    if not conf_get("DASHBOARD_TOKEN"):
        log("WARNING: DASHBOARD_TOKEN is empty — all logins will be refused "
            "(run 'sudo bash setup.sh --apply' to generate one)")
    # Re-adopt jobs that were running before our own restart (state derivation
    # in read_job handles the rest — nothing else to do here but log it).
    for j in list_jobs():
        if j.get("state") == "running":
            log(f"re-adopted running job: {j['id']} (pid {j.get('pid')})")

    t = threading.Thread(target=sampler_loop, daemon=True)
    t.start()

    srv = ThreadingHTTPServer(("0.0.0.0", port), Handler)
    srv.daemon_threads = True

    def shutdown(_sig, _frm):
        log("shutting down")
        threading.Thread(target=srv.shutdown, daemon=True).start()

    signal.signal(signal.SIGTERM, shutdown)
    signal.signal(signal.SIGINT, shutdown)

    log(f"web dashboard listening on 0.0.0.0:{port}")
    srv.serve_forever()
    log("stopped")


if __name__ == "__main__":
    main()
